"""Build first-pass data dictionary entries from deterministic artifacts.

This module combines profiling evidence, semantic suggestions, and optional
config overrides. Config can override assistive semantic wording, but not the
observed physical evidence generated by profiling.
"""

from __future__ import annotations
from typing import Any

from data_dictionary_agent.config import get_column_overrides, get_dataset_overrides
from data_dictionary_agent.constants import CONFIG_PROVENANCE_CAVEAT


DESCRIPTION_TEMPLATES = {
    "identifier": "Likely identifier field for records or related entities. Confirm exact business meaning and key behaviour.",
    "possible_sensitive": "Column name suggests possible personal or contact data. Review handling requirements before sharing or publishing.",
    "date": "Date-like field inferred from values and/or column name. Confirm business meaning.",
    "datetime": "Datetime-like field inferred from values and/or column name. Confirm timezone and business meaning.",
    "numeric_measure": "Numeric measure-like field. Confirm unit, calculation logic, and expected range.",
    "categorical": "Categorical field with a limited set of observed values. Confirm allowed values and definitions.",
    "boolean_flag": "Boolean or flag-like field. Confirm true/false meaning.",
    "free_text": "Free-text or notes-like field. Review examples to confirm intended use.",
    "unknown": "Business meaning could not be inferred confidently from deterministic evidence.",
}


def _to_display_name(column_name: str) -> str:
    words = str(column_name).replace("_", " ").strip().split()
    out: list[str] = []
    for word in words:
        if word.lower() == "id":
            out.append("ID")
        else:
            out.append(word.capitalize())
    return " ".join(out)


def _description_for(role: str, review_required: bool) -> tuple[str, str]:
    if review_required and role == "unknown":
        return "", "blank_review_required"
    return DESCRIPTION_TEMPLATES.get(role, DESCRIPTION_TEMPLATES["unknown"]), "deterministic_template"


def build_data_dictionary(profile: dict[str, Any], config: dict[str, Any] | None = None) -> dict[str, Any]:
    """Combine profile evidence and optional config into dictionary output."""
    entries: list[dict[str, Any]] = []
    for column in profile.get("columns", []):
        col_overrides = get_column_overrides(config, str(column.get("column_name", "")))
        role_overridden = "semantic_role" in col_overrides
        role = col_overrides.get("semantic_role", column.get("semantic_role", "unknown"))
        review_required = bool(col_overrides.get("review_required", column.get("review_required", False)))
        description, description_source = _description_for(role, review_required)
        if "description" in col_overrides:
            description, description_source = col_overrides.get("description", ""), "config_override"
        caveats = list(column.get("notes", [])) + list(column.get("review_notes", [])) + list(col_overrides.get("caveats", []))

        role_confidence = col_overrides.get("semantic_role_confidence", column.get("semantic_role_confidence"))
        # When a user overrides the semantic role without an explicit confidence,
        # keep provenance visible so reviewers know this confidence is contextual.
        if role_overridden and "semantic_role_confidence" not in col_overrides:
            role_confidence = "medium"
            caveats.append(CONFIG_PROVENANCE_CAVEAT)

        if column.get("semantic_role_confidence") == "low" and not role_overridden:
            caveats.append("Field requires review because semantic confidence is low.")
        if role == "identifier" and float(column.get("uniqueness_ratio", 0.0) or 0.0) < 0.95:
            caveats.append("Identifier-like field is not unique.")
        if role == "possible_sensitive":
            caveats.append("Possible sensitive field; classification requires human review.")
        if column.get("inferred_physical_type") == "mixed_or_unknown":
            caveats.append("Physical type is mixed_or_unknown.")

        generated_display_name = _to_display_name(str(column.get("column_name", "")))
        entry = {
            "column_name": column.get("column_name"),
            "display_name": col_overrides.get("display_name", generated_display_name),
            "display_name_source": "config_override" if "display_name" in col_overrides else "generated",
            "description": description,
            "description_source": description_source,
            "physical_type": column.get("inferred_physical_type"),
            "semantic_role": role,
            "semantic_role_source": "config_override" if "semantic_role" in col_overrides else "deterministic_inference",
            "semantic_role_confidence": role_confidence,
            "nullable": int(column.get("null_count", 0)) > 0,
            "null_count": column.get("null_count", 0),
            "null_ratio": column.get("null_ratio", 0.0),
            "distinct_count": column.get("distinct_count", 0),
            "uniqueness_ratio": column.get("uniqueness_ratio", 0.0),
            "sample_values": list(column.get("sample_values", [])),
            "top_values": list(column.get("top_values", [])),
            "min_value": column.get("min_value"),
            "max_value": column.get("max_value"),
            "review_required": review_required,
            "review_notes": list(column.get("review_notes", [])) + list(col_overrides.get("review_notes", [])),
            "sensitivity_hint": col_overrides.get("sensitivity_hint"),
            "allowed_values": list(col_overrides.get("allowed_values", [])),
            "business_rules": list(col_overrides.get("business_rules", [])),
            "owner": col_overrides.get("owner"),
            "domain": col_overrides.get("domain"),
            "source_system": col_overrides.get("source_system"),
            "caveats": list(dict.fromkeys(caveats)),
        }
        entries.append(entry)

    summary_counts = {
        "columns_needing_review": sum(1 for e in entries if e["review_required"]),
        "possible_sensitive_fields": sum(1 for e in entries if e["semantic_role"] == "possible_sensitive"),
        "identifier_like_fields": sum(1 for e in entries if e["semantic_role"] == "identifier"),
        "date_datetime_fields": sum(1 for e in entries if e["semantic_role"] in {"date", "datetime"}),
        "numeric_measures": sum(1 for e in entries if e["semantic_role"] == "numeric_measure"),
        "categorical_fields": sum(1 for e in entries if e["semantic_role"] == "categorical"),
    }

    dataset_overrides = get_dataset_overrides(config)
    return {
        "dataset": {
            "source_file": profile.get("file_name"),
            "input_path": profile.get("input_path"),
            "file_type": profile.get("file_type"),
            "sheet": profile.get("sheet_name"),
            "rows": profile.get("row_count", 0),
            "columns": profile.get("column_count", 0),
            "generated_at": profile.get("generated_at_utc"),
            "name": dataset_overrides.get("name"),
            "display_name": dataset_overrides.get("display_name"),
            "description": dataset_overrides.get("description"),
            "owner": dataset_overrides.get("owner"),
            "domain": dataset_overrides.get("domain"),
            "source_system": dataset_overrides.get("source_system"),
        },
        "columns": entries,
        "summary_counts": summary_counts,
        "review_item_counts": {
            "review_required": summary_counts["columns_needing_review"],
        },
    }
